In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
sns.set()

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
dataset = pd.get_dummies(dataset, columns=['Gender', 'Geography'], drop_first=True)

In [ ]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore  Age  Tenure    Balance  \
0          1    15634602  Hargrave          619   42       2       0.00   
1          2    15647311      Hill          608   41       1   83807.86   
2          3    15619304      Onio          502   42       8  159660.80   
3          4    15701354      Boni          699   39       1       0.00   
4          5    15737888  Mitchell          850   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0              1          1               1        101348.88       1   
1              1          0               1        112542.58       0   
2              3          1               0        113931.57       1   
3              2          0               0         93826.63       0   
4              1          1               1         79084.10       0   

   Gender_Male  Geography_Germany  Geography_Spain  
0            0                  0                0  
1            0                  0                1  
2            0                  0                0  
3            0                  0                0  
4            0                  0                1

In [ ]:
from sklearn.preprocessing import StandardScaler
columns_scaled=['Gender_Male', 'Geography_Germany','Geography_Spain','CreditScore','Age','Tenure','Balance','EstimatedSalary']
scaler = StandardScaler()
dataset[columns_scaled] = scaler.fit_transform(dataset[columns_scaled])

In [ ]:
dataset

RowNumber  CustomerId    Surname  CreditScore       Age    Tenure  \
0             1    15634602   Hargrave    -0.326221  0.293517 -1.041760   
1             2    15647311       Hill    -0.440036  0.198164 -1.387538   
2             3    15619304       Onio    -1.536794  0.293517  1.032908   
3             4    15701354       Boni     0.501521  0.007457 -1.387538   
4             5    15737888   Mitchell     2.063884  0.388871 -1.041760   
...         ...         ...        ...          ...       ...       ...   
9995       9996    15606229   Obijiaku     1.246488  0.007457 -0.004426   
9996       9997    15569892  Johnstone    -1.391939 -0.373958  1.724464   
9997       9998    15584532        Liu     0.604988 -0.278604  0.687130   
9998       9999    15682355  Sabbatini     1.256835  0.293517 -0.695982   
9999      10000    15628319     Walker     1.463771 -1.041433 -0.350204   

       Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0    -1.225848              1          1               1         0.021886   
1     0.117350              1          0               1         0.216534   
2     1.333053              3          1               0         0.240687   
3    -1.225848              2          0               0        -0.108918   
4     0.785728              1          1               1        -0.365276   
...        ...            ...        ...             ...              ...   
9995 -1.225848              2          1               0        -0.066419   
9996 -0.306379              1          1               1         0.027988   
9997 -1.225848              1          0               1        -1.008643   
9998 -0.022608              2          1               0        -0.125231   
9999  0.859965              1          1               0        -1.076370   

      Gender_Male  Geography_Germany  Geography_Spain  Exited  
0       -1.095988          -0.578736        -0.573809       1  
1       -1.095988          -0.578736         1.742740       0  
2       -1.095988          -0.578736        -0.573809       1  
3       -1.095988          -0.578736        -0.573809       0  
4       -1.095988          -0.578736         1.742740       0  
...           ...                ...              ...     ...  
9995     0.912419          -0.578736        -0.573809       0  
9996     0.912419          -0.578736        -0.573809       0  
9997    -1.095988          -0.578736        -0.573809       1  
9998     0.912419           1.727904        -0.573809       1  
9999    -1.095988          -0.578736        -0.573809       0  

[10000 rows x 15 columns]

In [ ]:
dataset = dataset.loc[:,['RowNumber',
 'CustomerId',
 'Surname',
 'CreditScore',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
  'Gender_Male',
 'Geography_Germany',
 'Geography_Spain',
   'Exited'
]]

In [ ]:
#Customer ID and Surname would not be relevant as features
X_columns = dataset.columns.tolist()[3:14]
Y_columns = dataset.columns.tolist()[-1:]
print(X_columns)
print(Y_columns)

['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Gender_Male', 'Geography_Germany', 'Geography_Spain']
['Exited']


In [ ]:
X = dataset[X_columns].values
Y = dataset[Y_columns].values

In [ ]:
#Spilt the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
#Let us create the Neural Network
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [ ]:
#Initialize ANN
classifier = Sequential()

In [ ]:
#Add input layer and hidden layer
classifier.add(Dense(6, activation = 'relu', input_shape = (X_train.shape[1], )))
classifier.add(Dropout(rate = 0.1))

In [ ]:
#Add second layer
classifier.add(Dense(6, activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

In [ ]:
#Add output layer
classifier.add(Dense(1, activation = 'sigmoid'))

In [ ]:
#Let us take a look at our network
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 6)                 72        
                                                                 
 dropout_2 (Dropout)         (None, 6)                 0         
                                                                 
 dense_4 (Dense)             (None, 6)                 42        
                                                                 
 dropout_3 (Dropout)         (None, 6)                 0         
                                                                 
 dense_5 (Dense)             (None, 1)                 7         
                                                                 
Total params: 121 (484.00 Byte)
Trainable params: 121 (484.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
#Optimize the weights
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
#Fitting the Neural Network
history = classifier.fit(X_train, y_train, batch_size = 32, epochs = 200, validation_split = 0.1, verbose = 2)

Epoch 1/200
225/225 - 0s - loss: 0.3666 - accuracy: 0.8512 - val_loss: 0.3344 - val_accuracy: 0.8600 - 450ms/epoch - 2ms/step
Epoch 2/200
225/225 - 1s - loss: 0.3693 - accuracy: 0.8482 - val_loss: 0.3356 - val_accuracy: 0.8537 - 538ms/epoch - 2ms/step
Epoch 3/200
225/225 - 0s - loss: 0.3676 - accuracy: 0.8533 - val_loss: 0.3340 - val_accuracy: 0.8625 - 325ms/epoch - 1ms/step
Epoch 4/200
225/225 - 0s - loss: 0.3662 - accuracy: 0.8496 - val_loss: 0.3385 - val_accuracy: 0.8575 - 324ms/epoch - 1ms/step
Epoch 5/200
225/225 - 0s - loss: 0.3685 - accuracy: 0.8510 - val_loss: 0.3346 - val_accuracy: 0.8637 - 315ms/epoch - 1ms/step
Epoch 6/200
225/225 - 0s - loss: 0.3660 - accuracy: 0.8506 - val_loss: 0.3342 - val_accuracy: 0.8612 - 282ms/epoch - 1ms/step
Epoch 7/200
225/225 - 0s - loss: 0.3630 - accuracy: 0.8553 - val_loss: 0.3347 - val_accuracy: 0.8600 - 333ms/epoch - 1ms/step
Epoch 8/200
225/225 - 0s - loss: 0.3674 - accuracy: 0.8500 - val_loss: 0.3330 - val_accuracy: 0.8600 - 317ms/epoch - 1

In [ ]:
y_pred = classifier.predict(X_test)
print(y_pred[:5])

63/63 [==============================] - 0s 1ms/step
[[0.28286538]
 [0.3036509 ]
 [0.20968744]
 [0.07732015]
 [0.08818138]]


In [ ]:
#Let us use confusion matrix with cutoff value as 0.5
y_pred = (y_pred > 0.5).astype(int)
print(y_pred[:5])

[[0]
 [0]
 [0]
 [0]
 [0]]


In [ ]:
#Making the Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1556   39]
 [ 237  168]]


In [ ]:
#Accuracy of our NN
print(((cm[0][0] + cm[1][1])* 100) / len(y_test), '% of data was classified correctly')

86.2 % of data was classified correctly
